# Generated by Django 2.1 on 2018-12-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField()),
                ('created', models.DateTimeField()),
                ('script', models.CharField(max_length=50)),
                ('arguments', models.CharField(max_length=100)),
                ('started', models.DateTimeField(null=True)),
                ('finished', models.DateTimeField(null=True)),
                ('diskspace_before', models.IntegerField(null=True)),
                ('diskspace_after', models.IntegerField(null=True)),
                ('retcode', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
